### PR TITLE
More changes

### PR DESCRIPTION
**Pull request by johndc7**
I'm back 😃 

Here's what I changed this time...
- Added `Promise` support
- Added a `forceJsonRequests` option to constructor. I found out that there is a `json=yes` query parameter that exists but makes the data return in a slightly different (and easier to work with in some cases) format. I added this option for backwards compatibility.
- Added `da.server.getDnsRecords()`. This will _only_ work with a `json=yes` query parameter (and yes it has to be in the query even on post requests for some reason). This is the bigger reason I added the JSON stuff.
- Updated `readme.md` so people know about the `forceJsonRequests` option. I said that it is recommended for new projects (and people that like fixing bugs on existing projects).

Also, maybe you should bump the version and publish to NPM?

### CODE REVIEW

**Comment by johndc7** [comment]
Any feedback on this?

**Comment by ThaDaVos** [comment]
I don't think this package is maintained any longer sadly - maybe, with permissions, someone else could pick it up as it's the only one out there

**Comment by johndc7** [comment]
Yea I still use it so I wouldn't have any problem maintaining it. I don't really have the need to make too many changes but I can handle the occasional issue / PR.

Unfortunately I don't think anyone is going to respond and I don't have permissions. I was thinking about publishing it on NPM under a different name.

**Comment by ThaDaVos** [comment]
If you're up for it - you could add me as contributor too - would love to help out the PR's and Issues if needed - I think it would be great to rebrand it under a different name but still link back to the original for credits

**Comment by johndc7** [comment]
@ThaDaVos 
Actually this package is just called `directadmin` on npm.

We could still call the new one `node-directadmin`. I can just publish my fork to npm.

**Comment by johndc7** [comment]
Closing PR as this repo doesn't seem to be maintained.

Fork located at [johndc7/node-directadmin](https://github.com/johndc7/node-directadmin)

**Pull request closed without merging**
